/* NAVYA shared UI */
(function(){
 const css='body{margin:0;font-family:Inter,system-ui,-apple-system,sans-serif;background:#f5f7fb;color:#172033}*{box-sizing:border-box}.top{height:64px;background:#111827;color:#fff;display:flex;align-items:center;justify-content:space-between;padding:0 24px}.brand{font-weight:900;letter-spacing:.12em}.user{font-size:13px;opacity:.9}.layout{display:flex;min-height:calc(100vh - 64px)}.side{width:250px;background:#fff;border-right:1px solid #e4e7ec;padding:16px;overflow:auto}.side a{display:block;padding:10px 12px;margin:3px 0;border-radius:9px;text-decoration:none;color:#344054;font-size:13px;font-weight:650}.side a:hover{background:#eef2ff;color:#3730a3}.main{flex:1;padding:26px;max-width:1500px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.card{background:#fff;border:1px solid #e4e7ec;border-radius:16px;padding:18px}.card h3{margin:0 0 7px}.muted{color:#667085}.num{font-size:28px;font-weight:900}.actions{display:flex;gap:10px;flex-wrap:wrap}.btn{border:0;border-radius:9px;padding:10px 14px;font-weight:800;cursor:pointer;background:#4f46e5;color:#fff}.btn.secondary{background:#eef2ff;color:#3730a3}.input{width:100%;padding:11px;border:1px solid #d0d5dd;border-radius:9px;font:inherit}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:11px;border-bottom:1px solid #eaecf0;text-align:left;font-size:13px}.tag{display:inline-block;padding:5px 8px;border-radius:999px;background:#eef2ff;color:#3730a3;font-size:12px;font-weight:700}@media(max-width:900px){.side{display:none}.grid{grid-template-columns:1fr 1fr}.main{padding:16px}}@media(max-width:560px){.grid{grid-template-columns:1fr}}';
 function inject(){if(document.getElementById('navya-ui-css'))return;const s=document.createElement('style');s.id='navya-ui-css';s.textContent=css;document.head.appendChild(s)}
 const common=[['Students','students.html'],['Teachers & Staff','teachers_staff.html'],['Academics','academics.html'],['Classes & Batches','classes_batches.html'],['Subjects','subjects.html'],['Attendance','attendance.html'],['Timetable','timetable.html'],['Homework','homework.html'],['Assignments','assignments.html'],['Question Bank','question_bank.html'],['Library','library.html'],['Test Builder','test_builder.html'],['Paper Designer','paper_designer.html'],['Online Exams','online_exams.html'],['Results','results.html'],['Communication','communication.html'],['Documents','documents.html'],['Video Center','video_center.html'],['PDF Slicer Studio','pdf_slicer_studio.html'],['Courses','courses.html']];
 const maps={
 OWNER:[...common,['Finance','finance.html'],['Admissions','admissions.html'],['Settings','settings.html']],
 ADMIN:[...common,['Finance','finance.html'],['Admissions','admissions.html'],['Settings','settings.html']],
 HOD:[['Dashboard','hod_dashboard.html'],...common.filter(x=>!['Finance','Admissions'].includes(x[0]))],
 TEACHER:[['Dashboard','teacher_dashboard.html'],...common.filter(x=>['Students','Academics','Classes & Batches','Subjects','Attendance','Timetable','Homework','Assignments','Question Bank','Library','Test Builder','Paper Designer','Online Exams','Results','Communication','Documents','Video Center','PDF Slicer Studio','Courses'].includes(x[0]))],
 STUDENT:[['Dashboard','student_dashboard.html'],['Academics','academics.html'],['Classes & Batches','classes_batches.html'],['Subjects','subjects.html'],['Homework','homework.html'],['Assignments','assignments.html'],['Library','library.html'],['Online Exams','online_exams.html'],['Results','results.html'],['Communication','communication.html'],['Courses','courses.html']],
 PARENT:[['Dashboard','parent_dashboard.html'],['Results','results.html'],['Attendance','attendance.html'],['Homework','homework.html'],['Assignments','assignments.html'],['Communication','communication.html']],
 ACCOUNTANT:[['Dashboard','accountant_dashboard.html'],['Students','students.html'],['Admissions','admissions.html'],['Finance','finance.html'],['Documents','documents.html'],['Communication','communication.html']],
 COUNSELOR:[['Dashboard','counselor_dashboard.html'],['Admissions','admissions.html'],['Students','students.html'],['Communication','communication.html'],['Documents','documents.html']]
 };
 window.NAVYA_UI={inject,session(){return NAVYA.session()},logout(){NAVYA.logout()},nav(role){const items=maps[role]||maps.TEACHER;return '<a href="'+(role==='SUPER_ADMIN'?'super_admin_dashboard.html':items[0][1])+'">Dashboard</a>'+items.filter(x=>x[0]!=='Dashboard').map(x=>'<a href="'+x[1]+'">'+x[0]+'</a>').join('')},protect(roles){const s=NAVYA.requireRole(roles);if(!s)return null;inject();return s},shell(title,role,s){inject();return '<header class="top"><div class="brand">NAVYA</div><div class="user">'+title+' · '+(s.name||s.email)+' <button class="btn secondary" onclick="NAVYA_UI.logout()" style="margin-left:10px">Logout</button></div></header><div class="layout"><aside class="side">'+NAVYA_UI.nav(role)+'</aside><main class="main"><h1 style="margin:0 0 5px">'+title+'</h1><div class="muted">'+(s.organizationName||'NAVYA Platform')+'</div>'},close(){return '</main></div>'}};
})();