/* NAVYA shared UI + Firebase data helpers */
(function(){
 const css='body{margin:0;font-family:Inter,system-ui,-apple-system,sans-serif;background:#f5f7fb;color:#172033}*{box-sizing:border-box}.top{height:64px;background:#111827;color:#fff;display:flex;align-items:center;justify-content:space-between;padding:0 24px}.brand{font-weight:900;letter-spacing:.12em}.user{font-size:13px;opacity:.9}.layout{display:flex;min-height:calc(100vh - 64px)}.side{width:240px;background:#fff;border-right:1px solid #e4e7ec;padding:18px}.side a{display:block;padding:10px 12px;margin:3px 0;border-radius:9px;text-decoration:none;color:#344054;font-size:14px;font-weight:650}.side a:hover{background:#eef2ff;color:#3730a3}.main{flex:1;padding:26px;max-width:1500px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.card{background:#fff;border:1px solid #e4e7ec;border-radius:16px;padding:18px}.card h3{margin:0 0 7px}.muted{color:#667085}.num{font-size:28px;font-weight:900}.actions{display:flex;gap:10px;flex-wrap:wrap}.btn{border:0;border-radius:9px;padding:10px 14px;font-weight:800;cursor:pointer;background:#4f46e5;color:#fff}.btn.secondary{background:#eef2ff;color:#3730a3}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:11px;border-bottom:1px solid #eaecf0;text-align:left;font-size:13px}.tag{display:inline-block;padding:5px 8px;border-radius:999px;background:#eef2ff;color:#3730a3;font-size:12px;font-weight:700}@media(max-width:900px){.side{display:none}.grid{grid-template-columns:1fr 1fr}.main{padding:16px}}@media(max-width:560px){.grid{grid-template-columns:1fr}}
';
 function inject(){const s=document.createElement('style');s.textContent=css;document.head.appendChild(s)}
 window.NAVYA_UI={inject,session(){return window.NAVYA&&NAVYA.session()},logout(){NAVYA.logout()},nav(role){const base=[['Dashboard','owner_dashboard.html'],['Students','students.html'],['Teachers & Staff','teachers_staff.html'],['Academics','academics.html'],['Classes & Batches','classes_batches.html'],['Subjects','subjects.html'],['Attendance','attendance.html'],['Timetable','timetable.html'],['Homework','homework.html'],['Assignments','assignments.html'],['Question Bank','question_bank.html'],['Library','library.html'],['Test Builder','test_builder.html'],['Paper Designer','paper_designer.html'],['Online Exams','online_exams.html'],['Results','results.html'],['Communication','communication.html'],['Finance','finance.html'],['Admissions','admissions.html'],['Documents','documents.html'],['Settings','settings.html']];return base.map(x=>'<a href="'+x[1]+'">'+x[0]+'</a>').join('')},
 protect(roles){const s=NAVYA.requireRole(roles);if(!s)return null;inject();return s},
 shell(title,role,s){return '<header class="top"><div class="brand">NAVYA</div><div>'+title+' · '+(s.name||s.email)+' <button class="btn secondary" onclick="NAVYA_UI.logout()" style="margin-left:10px">Logout</button></div></header><div class="layout"><aside class="side">'+NAVYA_UI.nav(role)+'</aside><main class="main"><div class="actions" style="justify-content:space-between"><div><h1 style="margin:0 0 5px">'+title+'</h1><div class="muted">'+(s.organizationName||'NAVYA Platform')+'</div></div></div>'},
 close(){return '</main></div>'},
 module(title,desc,items){return '<section class="card" style="margin-top:20px"><h2>'+title+'</h2><p class="muted">'+desc+'</p><div class="grid">'+items.map(x=>'<div class="card"><h3>'+x[0]+'</h3><p class="muted">'+x[1]+'</p><button class="btn secondary">Open</button></div>').join('')+'</div></section>'}
};
})();